// Auto-generated by LibreLane
module alu_8bit(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] a,
  input[7:0] b,
  input[2:0] opcode,
  output[7:0] result,
  output zero,
  output overflow
);
endmodule
