/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/alu_8bit.sv:1.1-58.10" *)
module alu_8bit(a, b, opcode, result, zero, overflow);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  (* src = "rtl/alu_8bit.sv:2.23-2.24" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "rtl/alu_8bit.sv:2.26-2.27" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "rtl/alu_8bit.sv:11.17-11.26" *)
  wire [7:0] b_operand;
  (* src = "rtl/alu_8bit.sv:10.11-10.23" *)
  wire cin_internal;
  (* src = "rtl/alu_8bit.sv:9.11-9.19" *)
  (* unused_bits = "0" *)
  wire cla_cout;
  (* src = "rtl/alu_8bit.sv:3.23-3.29" *)
  input [2:0] opcode;
  wire [2:0] opcode;
  (* src = "rtl/alu_8bit.sv:6.18-6.26" *)
  output overflow;
  wire overflow;
  (* src = "rtl/alu_8bit.sv:4.24-4.30" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "rtl/alu_8bit.sv:8.17-8.27" *)
  wire [7:0] sum_result;
  (* src = "rtl/alu_8bit.sv:5.18-5.22" *)
  output zero;
  wire zero;
  assign _072_ = ~opcode[2];
  assign _073_ = opcode[1] | ~(opcode[0]);
  assign cin_internal = _072_ & ~(_073_);
  assign _074_ = opcode[1] | opcode[0];
  assign _075_ = _072_ & ~(_074_);
  assign _076_ = ~(_075_ | cin_internal);
  assign _077_ = _073_ | _072_;
  assign _078_ = opcode[2] & ~(_074_);
  assign _079_ = _078_ | ~(_077_);
  assign _080_ = ~(opcode[1] & opcode[0]);
  assign _081_ = _072_ & ~(_080_);
  assign _082_ = opcode[0] | ~(opcode[1]);
  assign _083_ = _072_ & ~(_082_);
  assign _084_ = _083_ | _081_;
  assign _085_ = _084_ | _079_;
  assign _086_ = _076_ & ~(_085_);
  assign _087_ = _077_ | a[0];
  assign _088_ = ~(a[0] ^ b[0]);
  assign _089_ = _078_ & ~(_088_);
  assign _090_ = _087_ & ~(_089_);
  assign _091_ = ~(a[0] | b[0]);
  assign _092_ = _081_ & ~(_091_);
  assign _093_ = ~(a[0] & b[0]);
  assign _094_ = _083_ & ~(_093_);
  assign _095_ = _094_ | _092_;
  assign _096_ = _090_ & ~(_095_);
  assign _097_ = sum_result[0] & ~(_076_);
  assign _098_ = _097_ | ~(_096_);
  assign result[0] = _086_ ? a[0] : _098_;
  assign _099_ = ~(_077_ | a[1]);
  assign _100_ = ~(a[1] ^ b[1]);
  assign _101_ = _078_ & ~(_100_);
  assign _102_ = _101_ | _099_;
  assign _103_ = ~(a[1] | b[1]);
  assign _104_ = _081_ & ~(_103_);
  assign _105_ = ~(a[1] & b[1]);
  assign _106_ = _083_ & ~(_105_);
  assign _107_ = _106_ | _104_;
  assign _108_ = _107_ | _102_;
  assign _109_ = sum_result[1] & ~(_076_);
  assign _110_ = _109_ | _108_;
  assign result[1] = _086_ ? a[1] : _110_;
  assign _111_ = ~(_077_ | a[2]);
  assign _112_ = ~(a[2] ^ b[2]);
  assign _113_ = _078_ & ~(_112_);
  assign _114_ = _113_ | _111_;
  assign _115_ = ~(a[2] | b[2]);
  assign _116_ = _081_ & ~(_115_);
  assign _117_ = ~(a[2] & b[2]);
  assign _118_ = _083_ & ~(_117_);
  assign _119_ = _118_ | _116_;
  assign _120_ = _119_ | _114_;
  assign _121_ = sum_result[2] & ~(_076_);
  assign _000_ = _121_ | _120_;
  assign result[2] = _086_ ? a[2] : _000_;
  assign _001_ = ~(_077_ | a[3]);
  assign _002_ = ~(a[3] ^ b[3]);
  assign _003_ = _078_ & ~(_002_);
  assign _004_ = _003_ | _001_;
  assign _005_ = ~(a[3] | b[3]);
  assign _006_ = _081_ & ~(_005_);
  assign _007_ = ~(a[3] & b[3]);
  assign _008_ = _083_ & ~(_007_);
  assign _009_ = _008_ | _006_;
  assign _010_ = _009_ | _004_;
  assign _011_ = sum_result[3] & ~(_076_);
  assign _012_ = _011_ | _010_;
  assign result[3] = _086_ ? a[3] : _012_;
  assign _013_ = ~(_077_ | a[4]);
  assign _014_ = ~(a[4] ^ b[4]);
  assign _015_ = _078_ & ~(_014_);
  assign _016_ = _015_ | _013_;
  assign _017_ = ~(a[4] | b[4]);
  assign _018_ = _081_ & ~(_017_);
  assign _019_ = ~(a[4] & b[4]);
  assign _020_ = _083_ & ~(_019_);
  assign _021_ = _020_ | _018_;
  assign _022_ = _021_ | _016_;
  assign _023_ = sum_result[4] & ~(_076_);
  assign _024_ = _023_ | _022_;
  assign result[4] = _086_ ? a[4] : _024_;
  assign _025_ = ~(_077_ | a[5]);
  assign _026_ = ~(a[5] ^ b[5]);
  assign _027_ = _078_ & ~(_026_);
  assign _028_ = _027_ | _025_;
  assign _029_ = ~(a[5] | b[5]);
  assign _030_ = _081_ & ~(_029_);
  assign _031_ = ~(a[5] & b[5]);
  assign _032_ = _083_ & ~(_031_);
  assign _033_ = _032_ | _030_;
  assign _034_ = _033_ | _028_;
  assign _035_ = sum_result[5] & ~(_076_);
  assign _036_ = _035_ | _034_;
  assign result[5] = _086_ ? a[5] : _036_;
  assign _037_ = ~(_077_ | a[6]);
  assign _038_ = ~(a[6] ^ b[6]);
  assign _039_ = _078_ & ~(_038_);
  assign _040_ = _039_ | _037_;
  assign _041_ = ~(a[6] | b[6]);
  assign _042_ = _081_ & ~(_041_);
  assign _043_ = ~(a[6] & b[6]);
  assign _044_ = _083_ & ~(_043_);
  assign _045_ = _044_ | _042_;
  assign _046_ = _045_ | _040_;
  assign _047_ = sum_result[6] & ~(_076_);
  assign _048_ = _047_ | _046_;
  assign result[6] = _086_ ? a[6] : _048_;
  assign _049_ = ~a[7];
  assign _050_ = _049_ & ~(_077_);
  assign _051_ = ~(a[7] ^ b[7]);
  assign _052_ = _078_ & ~(_051_);
  assign _053_ = _052_ | _050_;
  assign _054_ = ~(a[7] | b[7]);
  assign _055_ = _081_ & ~(_054_);
  assign _056_ = ~(a[7] & b[7]);
  assign _057_ = _083_ & ~(_056_);
  assign _058_ = _057_ | _055_;
  assign _059_ = _058_ | _053_;
  assign _060_ = sum_result[7] & ~(_076_);
  assign _061_ = _060_ | _059_;
  assign result[7] = _086_ ? a[7] : _061_;
  assign _062_ = ~(result[1] | result[0]);
  assign _063_ = result[3] | result[2];
  assign _064_ = _062_ & ~(_063_);
  assign _065_ = result[5] | result[4];
  assign _066_ = result[7] | result[6];
  assign _067_ = _066_ | _065_;
  assign zero = _064_ & ~(_067_);
  assign b_operand[0] = cin_internal ^ b[0];
  assign b_operand[1] = cin_internal ^ b[1];
  assign b_operand[2] = cin_internal ^ b[2];
  assign b_operand[3] = cin_internal ^ b[3];
  assign b_operand[4] = cin_internal ^ b[4];
  assign b_operand[5] = cin_internal ^ b[5];
  assign b_operand[6] = cin_internal ^ b[6];
  assign _068_ = ~(cin_internal ^ b[7]);
  assign b_operand[7] = ~_068_;
  assign _069_ = _068_ ^ _049_;
  assign _070_ = result[7] ^ _049_;
  assign _071_ = _070_ | _069_;
  assign overflow = ~(_071_ | _076_);
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/alu_8bit.sv:15.14-21.6" *)
  cla_8bit adder_core (
    .a(a),
    .b(b_operand),
    .cin(cin_internal),
    .cout(cla_cout),
    .sum(sum_result)
  );
endmodule

(* src = "rtl/cla_4bit.sv:1.1-28.10" *)
module cla_4bit(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "rtl/cla_4bit.sv:2.23-2.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "rtl/cla_4bit.sv:2.26-2.27" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "rtl/cla_4bit.sv:7.17-7.18" *)
  (* unused_bits = "1 2 3" *)
  wire [4:0] c;
  (* src = "rtl/cla_4bit.sv:3.17-3.20" *)
  input cin;
  wire cin;
  (* src = "rtl/cla_4bit.sv:5.18-5.22" *)
  output cout;
  wire cout;
  (* src = "rtl/cla_4bit.sv:4.24-4.27" *)
  output [3:0] sum;
  wire [3:0] sum;
  assign _00_ = b[3] & a[3];
  assign _01_ = b[3] ^ a[3];
  assign _02_ = ~(b[2] & a[2]);
  assign _03_ = _01_ & ~(_02_);
  assign _04_ = _03_ | _00_;
  assign _05_ = ~(b[2] ^ a[2]);
  assign _06_ = _01_ & ~(_05_);
  assign _07_ = ~(b[1] & a[1]);
  assign _08_ = _06_ & ~(_07_);
  assign _09_ = _08_ | _04_;
  assign _10_ = b[1] ^ a[1];
  assign _11_ = ~(_10_ & _06_);
  assign _12_ = b[0] & a[0];
  assign _13_ = _12_ & ~(_11_);
  assign _14_ = _13_ | _09_;
  assign _15_ = ~(b[0] ^ a[0]);
  assign _16_ = _15_ | _11_;
  assign _17_ = cin & ~(_16_);
  assign cout = _17_ | _14_;
  assign sum[0] = ~(_15_ ^ cin);
  assign _18_ = ~(b[1] ^ a[1]);
  assign _19_ = ~(b[0] & a[0]);
  assign _20_ = cin & ~(_15_);
  assign _21_ = _19_ & ~(_20_);
  assign sum[1] = _21_ ^ _18_;
  assign _22_ = _10_ & ~(_19_);
  assign _23_ = _07_ & ~(_22_);
  assign _24_ = _15_ | _18_;
  assign _25_ = cin & ~(_24_);
  assign _26_ = _23_ & ~(_25_);
  assign sum[2] = _26_ ^ _05_;
  assign _27_ = ~(_07_ | _05_);
  assign _28_ = _02_ & ~(_27_);
  assign _29_ = _18_ | _05_;
  assign _30_ = _12_ & ~(_29_);
  assign _31_ = _28_ & ~(_30_);
  assign _32_ = _29_ | _15_;
  assign _33_ = cin & ~(_32_);
  assign _34_ = _33_ | ~(_31_);
  assign sum[3] = _34_ ^ _01_;
  assign { c[4], c[0] } = { cout, cin };
endmodule

(* src = "rtl/cla_8bit.sv:1.1-23.10" *)
module cla_8bit(a, b, cin, sum, cout);
  (* src = "rtl/cla_8bit.sv:2.23-2.24" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "rtl/cla_8bit.sv:2.26-2.27" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "rtl/cla_8bit.sv:7.11-7.13" *)
  wire c4;
  (* src = "rtl/cla_8bit.sv:3.17-3.20" *)
  input cin;
  wire cin;
  (* src = "rtl/cla_8bit.sv:5.18-5.22" *)
  output cout;
  wire cout;
  (* src = "rtl/cla_8bit.sv:4.24-4.27" *)
  output [7:0] sum;
  wire [7:0] sum;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cla_8bit.sv:16.14-22.6" *)
  cla_4bit high_nibble (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(c4),
    .cout(cout),
    .sum(sum[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/cla_8bit.sv:8.14-14.6" *)
  cla_4bit low_nibble (
    .a(a[3:0]),
    .b(b[3:0]),
    .cin(cin),
    .cout(c4),
    .sum(sum[3:0])
  );
endmodule
